<?php
	session_start();
	if(isset($_SESSION['email'])==false){
		header('location:Home.php');
	}
	$email=$_SESSION['email'];

 ?>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
		<?php
			include("header.php");			
			include("menu1.php");
		?>
					<br>
					<br>
		<div><center><h2>Here Is Your Cycle Details</h2></center></div>
					<br>
					<br>
					<br>
			<div>
			<center><?php
					include("cC.php");?>
			</center>
			</div>
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
</body>
	<?php
		include("footer.php");
	?>
</html>
